### ISSUE TITLE
Not working with Security Breach RUIN files

### ISSUE THREAD

**Issue by lynrayy** [florensie/ue-wwise-extractor#5]
You can test your script by yourself, it is not works https://drive.google.com/file/d/1fAfzPvywwH6py2C_mjEBrAoghsFGC_CV/view?usp=sharing

_"The readme states that "The script was only tested with Satisfactory". I can't provide help with anything else"_ 
So what? The fact script tested only with "Satisfactory" does not means that script not needed in fixes

**Comment by florensie** [comment]
Duplicate of #4.

Many games do these things differently, and this was a one-off project. Feel free to contribute a fix yourself, but I am under no obligation to spend my valued time to fix this for you.
